modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/dye-extension/issues" #optional
[[mods]]
    modId="dye_extension" #mandatory
    version="${file.jarVersion}" #mandatory
    displayName="Dye Extension"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/dye-extension" #optional
    # A file name (in the root of the mod JAR) containing a logo for display
    # logoFile="examplemod.png" #optional
    authors="justAm0dd3r" #optional
    description='''
    Adds dyed sticks and all kinds of tools with dyed handles to the game. It also adds some dyed blocks (dyed cobblestone and dyed leaves)
    '''

[[dependencies.dye_extension]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.dye_extension]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2, 1.16.1]"
    ordering="NONE"
    side="BOTH"
