modLoader="javafml"
loaderVersion="[32,)"
license="General Public License v3"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/dye-extension/issues"
[[mods]]
    modId="dye_extension"
    version="${file.jarVersion}"
    displayName="Dye Extension"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/dye-extension" #optional
    # A file name (in the root of the mod JAR) containing a logo for display
    # logoFile="examplemod.png" #optional
    updateJSONURL="https://raw.githubusercontent.com/Krxwallo/ModUpdates/master/dye-extension/update.json"
    authors="justAm0dd3r"
    description='''
    Adds dyed sticks and all kinds of tools with dyed handles to the game. It also adds some dyed blocks (dyed cobblestone and dyed leaves)
    '''

[[dependencies.dye_extension]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.dye_extension]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1, 1.17)"
    ordering="NONE"
    side="BOTH"
